### ISSUE TITLE
Support Uploading multiple files

### ISSUE THREAD

**Issue by johrstrom** [rseng/zenodo-release#5]
For Open OnDemand, it's likely the artifact in use (the one being cited) is an `.rpm` package and not the source code.  

So in my case, I'd like to upload many files. Namely, The source tar and packages like `rpm` and `deb`. Ruby's really good with fileglobs, so I tend to use them a lot and think most folks would want to ** directories.

```yaml
with:
  files:
    # specific files
    - 'packaging/rpm/cool-package-{{ version }}.rpm'
  
    # with globs
    - 'packaging/deb/cool_package*'
```
